name: password_text_field
description: PasswordTextField is a TextField that manages the toggle of obscure.
version: 1.2.0
homepage: https://github.com/koji-1009/password_text_field

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
