name: password_text_field
description: PasswordTextField is a TextField that manages the toggle of obscure.
version: 0.0.2
homepage: https://github.com/koji-1009/password_text_field

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0
