name: analyze

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: koji-1009/setup-flutter@26fb6927d2874fcc9b3af19cb4cf5cd66ec18a28 # v1.3.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart analyze

  format:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: koji-1009/setup-flutter@26fb6927d2874fcc9b3af19cb4cf5cd66ec18a28 # v1.3.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .

  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: koji-1009/setup-flutter@26fb6927d2874fcc9b3af19cb4cf5cd66ec18a28 # v1.3.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
